I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 19, in script call
    call episode4
  File "game/episode4.rpy", line 15, in script
    scene camp room with open_eye
  File "game/episode4.rpy", line 15, in <module>
    scene camp room with open_eye
NameError: name 'open_eye' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 19, in script call
    call episode4
  File "game/episode4.rpy", line 15, in script
    scene camp room with open_eye
  File "C:\Program Files\renpy-7.1.3-sdk\renpy\ast.py", line 1352, in execute
    paired = renpy.python.py_eval(self.paired)
  File "C:\Program Files\renpy-7.1.3-sdk\renpy\python.py", line 1944, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Program Files\renpy-7.1.3-sdk\renpy\python.py", line 1937, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/episode4.rpy", line 15, in <module>
    scene camp room with open_eye
NameError: name 'open_eye' is not defined

Windows-8-6.2.9200
Ren'Py 7.1.3.1092
Winter Friend Story 1.0
Mon Dec 31 19:28:53 2018
